/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CataloguesRouteImport } from './routes/catalogues'
import { Route as IndexRouteImport } from './routes/index'

const CataloguesRoute = CataloguesRouteImport.update({
  id: '/catalogues',
  path: '/catalogues',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalogues': typeof CataloguesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalogues': typeof CataloguesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalogues': typeof CataloguesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/catalogues'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/catalogues'
  id: '__root__' | '/' | '/catalogues'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CataloguesRoute: typeof CataloguesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/catalogues': {
      id: '/catalogues'
      path: '/catalogues'
      fullPath: '/catalogues'
      preLoaderRoute: typeof CataloguesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CataloguesRoute: CataloguesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
